---
  database:
    host: "dbtut.cg9hvcbz8wtg.ca-central-1.rds.amazonaws.com"
    port: 5432
    dbname: "dbtut"
    user: "postgres"
    password: "Mostafa1360"
  aws:
    accessKey: "AKIAXGDMHGBWIK4D7RE2"
    secretKey: "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"
  s3:
    outputBucketName: 'tutexample13-sources-tutoutputbucket-c7494mx9cspn'
    outputFileBaseName: 'outputFile'