---
  database:
    host: "dbtut.cg9hvcbz8wtg.ca-central-1.rds.amazonaws.com"
    port: 5432
    dbname: "dbtut"
    user: "postgres"
    password: "Mostafa1360"
  aws:
    accessKey: "PUT_YOUR_ACCESS_KEY_HERE"
    secretKey: "PUT_YOUR_SECRET_KEY_HERE"
  s3:
    outputBucketName: 'tutexample13-sources-tutoutputbucket-c7494mx9cspn'
    outputFileBaseName: 'outputFile'
