---
AWSTemplateFormatVersion: '2010-09-09'
Description: >

  This Cloudformation Template deploys the Database Cluster (Amazon Aurora) for the Tutorial application infrastructure.

  Disclaimer: Not for production use. Demo and testing purposes only.

  Author: Mostafa Rezaei <mostafa.ezaeir@gmail.com>

Parameters:
  TUTDBName:
    Description: Database Name
    Type: String
    Default: tutdb
  TUTDBPort:
    Description: TCP/IP Port for the Database Instance
    Type: Number
    Default: 5432
  TUTDBInstanceType:
    Description: DB RDS instance type
    Type: String
    Default: db.t3.medium
    AllowedValues:
      - serverless
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
      - db.t3.2xlarge
  TUTServerlessAuroraMinCapacity:
    Description: The minimum capacity for the Amazon Aurora Serverless Cluster.
    Type: Number
    Default: 2
  TUTServerlessAuroraMaxCapacity:
    Description: The maximum capacity for the Amazon Aurora Serverless Cluster
    Type: Number
    Default: 4
  TUTDBEngineVersion:
    Description: Database engine version for Aurora PostgreSQL
    Type: String
    Default: 10.7
  TUTEnvironmentStage:
    Type: String
    Description: Select the appropriate environment
    AllowedValues:
      - stage
      - prod
      - dev

Conditions:
  TUTProdEnvironment: !Equals [ !Ref TUTEnvironmentStage, prod ]
  TUTNonProdEnvironment: !Not [ Condition: TUTProdEnvironment ]
  TUTServerlessAurora: !Equals [ !Ref TUTDBInstanceType, serverless ]
  TUTProvisionedAurora: !Not [ Condition: TUTServerlessAurora ]
  TUTProvisiondedProdAurora: !And
    - !Not [ Condition: TUTServerlessAurora ]
    - Condition: TUTProdEnvironment

Resources:
  TUTRDSDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the TUT Database instance secret'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "TUTDBUsr"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludePunctuation: 'true'

  TUTRDSDBConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the TUT Database cluster url secret'
      SecretString: !Sub
        - '{"hostname": "${HOSTNAME}", "port": ${PORT}, "connectionString": "postgresql://${TUTDBUser}:${TUTDBPassword}@${HOSTNAME}:${PORT}"}'
        - HOSTNAME:
            Fn::GetAtt:
              - TUTRDSCluster
              - Endpoint.Address
          PORT:
            Fn::GetAtt:
              - TUTRDSCluster
              - Endpoint.Port
          TUTDBUser: !Join [ '', [ '{{resolve:secretsmanager:', !Ref TUTRDSDBSecret, ':SecretString:username}}' ] ]
          TUTDBPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref TUTRDSDBSecret, ':SecretString:password}}' ] ]

  TUTRDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref TUTRDSDBSecret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref TUTRDSDBSecret, ':SecretString:password}}' ] ]
      DatabaseName: !Join [ '_', [ !Ref TUTDBName, !Ref TUTEnvironmentStage ] ]
      Port:
        Ref: TUTDBPort
      Engine: aurora-postgresql
      EngineVersion:
        Ref: TUTDBEngineVersion
      EngineMode: !If [ TUTServerlessAurora, serverless, provisioned ]
      StorageEncrypted: 'true'
      DBClusterParameterGroupName:
        Ref: "TUTRDSDBClusterParameterGroupPostgres"
      ScalingConfiguration:
        !If
        - TUTServerlessAurora
        - AutoPause: true
          MinCapacity: !Ref TUTServerlessAuroraMinCapacity
          MaxCapacity: !Ref TUTServerlessAuroraMaxCapacity
          SecondsUntilAutoPause: 300
        - !Ref "AWS::NoValue"

  TUTRDSDBInstance1:
    Type: AWS::RDS::DBInstance
    Condition: TUTProvisionedAurora
    Properties:
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      CopyTagsToSnapshot: 'true'
      Engine: aurora-postgresql
      EngineVersion:
        Ref: TUTDBEngineVersion
      DBClusterIdentifier:
        Ref: TUTRDSCluster
      DBParameterGroupName:
        Ref: TUTRDSDBParameterGroupPostgres
      AvailabilityZone:
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region
      DBInstanceClass:
        Ref: TUTDBInstanceType

  TUTRDSDBInstance2:
    Type: AWS::RDS::DBInstance
    Condition: TUTProvisiondedProdAurora
    Properties:
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      CopyTagsToSnapshot: 'true'
      Engine: aurora-postgresql
      EngineVersion:
        Ref: TUTDBEngineVersion
      DBClusterIdentifier:
        Ref: TUTRDSCluster
      AvailabilityZone:
        Fn::Select:
          - '1'
          - Fn::GetAZs:
              Ref: AWS::Region
      DBInstanceClass:
        Ref: TUTDBInstanceType

  TUTRDSDBParameterGroupPostgres:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Aurora PG 12 Database Instance Parameter Group for Cloudformation Stack
      Family: !If [ TUTServerlessAurora, aurora-postgresql10, aurora-postgresql12 ]
      Parameters:
        shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
        log_statement: "ddl"
        log_connections: 1
        log_disconnections: 1
        log_lock_waits: 1
        log_min_duration_statement: 5000
        auto_explain.log_min_duration: 5000
        auto_explain.log_verbose: 1
        log_rotation_age: 1440
        log_rotation_size: 102400
        rds.log_retention_period: 10080
        random_page_cost: 1
        track_activity_query_size: 16384
        idle_in_transaction_session_timeout: 7200000
        statement_timeout: 7200000
        search_path: '"$user",public'

  TUTRDSDBClusterParameterGroupPostgres:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: CloudFormation Sample Aurora Cluster PG Parameter Group
      Family: !If [ TUTServerlessAurora, aurora-postgresql10, aurora-postgresql12 ]
      Parameters:
        timezone: Europe/Berlin

  DBClusterEventSubscription:
    Type: 'AWS::RDS::EventSubscription'
    Properties:
      EventCategories:
        - failover
        - failure
        - notification
      SourceIds:
        - Ref: TUTRDSCluster
      SourceType: 'db-cluster'

Outputs:
  TUTDB:
    Description: The TUT Database Created
    Value:
      Ref: TUTRDSCluster
  TUTRDSDBConnectionSecret:
    Description: The TUT DB Connection Data
    Value:
      Ref: TUTRDSDBConnectionSecret
  TUTRDSDBSecret:
    Description: The TUT DB Login Data
    Value:
      Ref: TUTRDSDBSecret
  TUTRDSDBClusterParameterGroup:
    Description: The TUT DB Cluster Parameter Group
    Value:
      Ref: "TUTRDSDBClusterParameterGroupPostgres"
  TUTRDSCluster:
    Description: The TUT DB Cluster
    Value:
      Ref: TUTRDSCluster
  TUTRDSDBInstance1:
    Condition: TUTProvisionedAurora
    Description: The TUT DB Instance 1
    Value:
      Ref: TUTRDSDBInstance1
  TUTRDSDBInstance2:
    Condition: TUTProvisiondedProdAurora
    Description: The TUT DB Instance 2
    Value:
      Ref: TUTRDSDBInstance2
  TUTRDSDBParameterGroup:
    Description: The TUT DB Parameter Group
    Value:
      Ref: "TUTRDSDBParameterGroupPostgres"
